"""Curated NOVA company registry.

This file is deliberately separate from ranking. A company being present here, or
having a richer profile, never adds ranking score. It only supplies identity and
profile metadata after a result has already been discovered.
"""

def profile(organization, category, tagline="", description="", accent="#2563eb", links=None, tier="showcase"):
    return {
        "organization": organization,
        "category": category,
        "tagline": tagline,
        "description": description,
        "profile_accent": accent,
        "profile_tier": tier,
        "profile_badge": "NOVA Profile" if tier == "showcase" else "",
        "links": links or {},
    }


REGISTRY = {
    "google.com": profile("Google", "Technology", "Интернет-сервисы и технологии", "Официальный домен Google.", "#4285f4", {"about":"https://about.google/","careers":"https://careers.google.com/"}),
    "youtube.com": profile("YouTube", "Media", "Видео и создатели", "Официальный домен YouTube.", "#ff0033", {"about":"https://about.youtube/"}),
    "github.com": profile("GitHub", "Developer Tools", "Платформа для совместной разработки", "Официальный домен GitHub.", "#24292f", {"about":"https://github.com/about","docs":"https://docs.github.com/"}),
    "microsoft.com": profile("Microsoft", "Technology", "Программное обеспечение, облако и AI", "Официальный домен Microsoft.", "#5e5e5e", {"about":"https://www.microsoft.com/about","support":"https://support.microsoft.com/"}),
    "apple.com": profile("Apple", "Technology", "Устройства, сервисы и программное обеспечение", "Официальный домен Apple.", "#111111", {"newsroom":"https://www.apple.com/newsroom/","support":"https://support.apple.com/"}),
    "openai.com": profile("OpenAI", "AI", "Исследования и продукты искусственного интеллекта", "Официальный домен OpenAI.", "#111111", {"about":"https://openai.com/about/","careers":"https://openai.com/careers/"}),
    "meta.com": profile("Meta", "Technology", "Социальные технологии и AI", "Официальный корпоративный домен Meta.", "#0866ff", {"about":"https://about.meta.com/","careers":"https://www.metacareers.com/"}),
    "facebook.com": profile("Facebook", "Social", "Социальная сеть", "Официальный домен Facebook.", "#1877f2"),
    "instagram.com": profile("Instagram", "Social", "Фото, видео и общение", "Официальный домен Instagram.", "#c13584"),
    "whatsapp.com": profile("WhatsApp", "Messaging", "Личные и бизнес-коммуникации", "Официальный домен WhatsApp.", "#25d366"),
    "linkedin.com": profile("LinkedIn", "Professional Network", "Профессиональная сеть", "Официальный домен LinkedIn.", "#0a66c2", {"about":"https://about.linkedin.com/"}),
    "reddit.com": profile("Reddit", "Community", "Сообщества и обсуждения", "Официальный домен Reddit.", "#ff4500"),
    "x.com": profile("X", "Social", "Публичные разговоры и обновления", "Официальный домен X.", "#111111"),
    "tiktok.com": profile("TikTok", "Social", "Короткие видео и сообщества", "Официальный домен TikTok.", "#111111"),
    "discord.com": profile("Discord", "Communication", "Сообщества, голос и сообщения", "Официальный домен Discord.", "#5865f2", {"support":"https://support.discord.com/"}),
    "spotify.com": profile("Spotify", "Media", "Музыка, подкасты и аудио", "Официальный домен Spotify.", "#1db954", {"about":"https://www.spotify.com/about-us/","support":"https://support.spotify.com/"}),
    "netflix.com": profile("Netflix", "Media", "Стриминговый сервис", "Официальный домен Netflix.", "#e50914", {"about":"https://about.netflix.com/","help":"https://help.netflix.com/"}),
    "amazon.com": profile("Amazon", "Commerce", "Онлайн-торговля и технологии", "Официальный глобальный домен Amazon.", "#ff9900", {"about":"https://www.aboutamazon.com/","jobs":"https://www.amazon.jobs/"}),
    "amazon.de": profile("Amazon", "Commerce", "Онлайн-торговля и технологии", "Официальный домен Amazon.", "#ff9900"),
    "ebay.com": profile("eBay", "Commerce", "Онлайн-маркетплейс", "Официальный домен eBay.", "#3665f3"),
    "paypal.com": profile("PayPal", "Fintech", "Цифровые платежи", "Официальный домен PayPal.", "#003087"),
    "stripe.com": profile("Stripe", "Fintech", "Платёжная инфраструктура для интернета", "Официальный домен Stripe.", "#635bff", {"about":"https://stripe.com/about","docs":"https://docs.stripe.com/"}),
    "shopify.com": profile("Shopify", "Commerce", "Платформа для интернет-магазинов", "Официальный домен Shopify.", "#5e8e3e", {"about":"https://www.shopify.com/about","help":"https://help.shopify.com/"}),
    "cloudflare.com": profile("Cloudflare", "Internet Infrastructure", "Сеть, безопасность и производительность", "Официальный домен Cloudflare.", "#f48120", {"about":"https://www.cloudflare.com/about-overview/","docs":"https://developers.cloudflare.com/"}),
    "nvidia.com": profile("NVIDIA", "Technology", "Вычисления, графика и AI", "Официальный домен NVIDIA.", "#76b900", {"about":"https://www.nvidia.com/about-nvidia/","developer":"https://developer.nvidia.com/"}),
    "intel.com": profile("Intel", "Semiconductors", "Полупроводники и вычислительные платформы", "Официальный домен Intel.", "#0068b5"),
    "amd.com": profile("AMD", "Semiconductors", "Процессоры и графические технологии", "Официальный домен AMD.", "#ed1c24"),
    "adobe.com": profile("Adobe", "Software", "Креативные и документные продукты", "Официальный домен Adobe.", "#ff0000", {"about":"https://www.adobe.com/about-adobe.html","support":"https://helpx.adobe.com/support.html"}),
    "salesforce.com": profile("Salesforce", "Enterprise Software", "CRM и корпоративные облачные продукты", "Официальный домен Salesforce.", "#0d9dda"),
    "oracle.com": profile("Oracle", "Enterprise Software", "Базы данных и облачная инфраструктура", "Официальный домен Oracle.", "#c74634"),
    "ibm.com": profile("IBM", "Technology", "Корпоративные технологии и AI", "Официальный домен IBM.", "#0f62fe"),
    "notion.so": profile("Notion", "Productivity", "Рабочее пространство для заметок и команд", "Официальный домен Notion.", "#111111", {"help":"https://www.notion.so/help"}),
    "figma.com": profile("Figma", "Design", "Совместный дизайн интерфейсов", "Официальный домен Figma.", "#a259ff", {"about":"https://www.figma.com/about-us/","community":"https://www.figma.com/community"}),
    "canva.com": profile("Canva", "Design", "Визуальная коммуникация и дизайн", "Официальный домен Canva.", "#7d2ae8", {"about":"https://www.canva.com/about/","help":"https://www.canva.com/help/"}),
    "slack.com": profile("Slack", "Communication", "Командные коммуникации", "Официальный домен Slack.", "#611f69", {"help":"https://slack.com/help"}),
    "zoom.us": profile("Zoom", "Communication", "Видеосвязь и совместная работа", "Официальный домен Zoom.", "#2d8cff", {"support":"https://support.zoom.com/"}),
    "dropbox.com": profile("Dropbox", "Cloud Storage", "Хранение и совместная работа с файлами", "Официальный домен Dropbox.", "#0061ff"),
    "atlassian.com": profile("Atlassian", "Developer Tools", "Инструменты для команд разработки и бизнеса", "Официальный домен Atlassian.", "#1868db"),
    "steamcommunity.com": profile("Steam", "Games", "Игры, магазин и сообщество", "Официальный домен Steam.", "#1b2838"),
    "steampowered.com": profile("Steam", "Games", "Игры, магазин и сообщество", "Официальный домен Steam.", "#1b2838"),
    "epicgames.com": profile("Epic Games", "Games", "Игры и игровые технологии", "Официальный домен Epic Games.", "#111111"),
    "riotgames.com": profile("Riot Games", "Games", "Игры и киберспорт", "Официальный домен Riot Games.", "#d32936"),
    "ea.com": profile("Electronic Arts", "Games", "Видеоигры и интерактивные развлечения", "Официальный домен Electronic Arts.", "#ff4747"),
    "ubisoft.com": profile("Ubisoft", "Games", "Видеоигры", "Официальный домен Ubisoft.", "#0070ff"),
    "roblox.com": profile("Roblox", "Games", "Игровая и пользовательская платформа", "Официальный домен Roblox.", "#111111"),
    "sony.com": profile("Sony", "Technology", "Электроника и развлечения", "Официальный корпоративный домен Sony.", "#003791"),
    "nintendo.com": profile("Nintendo", "Games", "Игровые устройства и игры", "Официальный домен Nintendo.", "#e60012"),
    "samsung.com": profile("Samsung", "Technology", "Электроника и устройства", "Официальный домен Samsung.", "#1428a0"),
    "tesla.com": profile("Tesla", "Automotive", "Электромобили и энергетика", "Официальный домен Tesla.", "#cc0000"),
    "bmw.com": profile("BMW", "Automotive", "Автомобили и мобильность", "Официальный глобальный домен BMW.", "#0066b1"),
    "mercedes-benz.com": profile("Mercedes-Benz", "Automotive", "Автомобили и мобильность", "Официальный домен Mercedes-Benz.", "#111111"),
    "volkswagen.com": profile("Volkswagen", "Automotive", "Автомобили и мобильность", "Официальный глобальный домен Volkswagen.", "#001e50"),
    "uber.com": profile("Uber", "Mobility", "Поездки, доставка и логистика", "Официальный домен Uber.", "#111111"),
    "airbnb.com": profile("Airbnb", "Travel", "Жильё и путешествия", "Официальный домен Airbnb.", "#ff385c"),
    "booking.com": profile("Booking.com", "Travel", "Бронирование путешествий", "Официальный домен Booking.com.", "#003b95"),
    "nike.com": profile("Nike", "Apparel", "Спортивная одежда и товары", "Официальный домен Nike.", "#111111"),
    "adidas.com": profile("adidas", "Apparel", "Спортивная одежда и товары", "Официальный глобальный домен adidas.", "#111111"),
    "ikea.com": profile("IKEA", "Retail", "Мебель и товары для дома", "Официальный глобальный домен IKEA.", "#0058a3"),
}
